golang-jwt/jwt

.github/workflows/build.yml
go.mod

I have added a simple GitHub actions file. I have intentionally left the go module path as the original package name for now - knowing that this needs to change.
This is basically just to see that everything works.
Closes #2

Added GitHub actions

---

.github/workflows/build.yml
README.md

Along with a maunal step in github UI to rename default branch this PR fixes #13

Rename default branch references to main

---

LICENSE

Add the golang-jwt mainteiners as additional copyright holders on modifications to the initial work

Add copyright notice to LICENSE

---

.github/workflows/build.yml
go.mod

As discussed in full length here (#17), we have run into issues that forces us to abandon go modules, at least for the `v3.x.x` releases. After this is merged in, we can release a `v3.2.1+incompatible` version, which contains a security fix. 
Afterwards, we will work on non-breaking quality of life fixes and then eventually run a `v4` version, which most likely will then support go modules and have a new SIV-style import path.
Also note that according to https://blog.golang.org/go116-module-changes, building from $GOPATH will be *removed* in Go 1.17. So most likely, only the `v4` SIV-style releases will be supported by Go 1.17. However, I can not find anything with regards to this on the upcoming release notes (http://tip.golang.org/doc/go1.17)

Removing `go.mod` for v3 releases

---

ecdsa.go
ecdsa_test.go
parser_test.go
token.go

Add benchmark coverage of ECDSA signing methods.
Reduce memory allocations for ECDSA signing by using [big.Int.FillBytes](https://golang.org/pkg/math/big/#Int.FillBytes
) instead of allocating and copying bytes directly.
`FillBytes` was added in go 1.15.
> FillBytes sets buf to the absolute value of x, storing it as a zero-extended big-endian byte slice, and returns buf.
Use [base64.RawURLEncoding](https://golang.org/pkg/encoding/base64/#pkg-variables) to avoid having to add and remove `=` padding.
> RawURLEncoding ... is the same as URLEncoding but omits padding characters.
```
$ go test --bench=Bench --run=NONE .
goos: darwin
goarch: amd64
pkg: github.com/golang-jwt/jwt
```
Before optimizations, as of ff7295fc94e1d37ba46fd2a0ce9f10454551a2e2:
```
BenchmarkECDSASigning/Basic_ES256-8 …
```

Allocation optimization

---

VERSION_HISTORY.md

Prepare release 3.2.2

---

README.md

Otherwise, people will end up at the v3 release and might miss on clicking the small "there is a v4 hint" on pkg.go.dev

Changing pkg.go.dev URL to github.com/golang-jwt/jwt/v4

---

claims.go
map_claims.go

jwt: Fix Verify methods documentation

---

ed25519.go

in order to allow usage of other ed25519 providers than crypto/ed25519
For example in my case I use a HSM (YubiHSM2), which means the private key is not visible to the go code (can't check its len, etc), however it is indeed a ed25519 key and the object provides the Sign() method
The HSM lib: https://github.com/KarpelesLab/hsm

Accept `crypto.Signer` that contains a `ed25519.PublicKey` in ed25519

---

claims.go
map_claims_test.go

https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4
>  The "exp" (expiration time) claim identifies the expiration time on
or after which the JWT MUST NOT be accepted for processing.
it is written on the reference.
So, it seems invalid when exp indicates the present. Isn't it right?

When exp indicates the present, make it invalid.

---

parser_test.go
request/request_test.go
test/helpers.go

In parse_test.go:
1. add test case where the JWT token is signed with a ECDSA private key and "EC256" is in the list of accepted algorithms.
1. add test case where the JWT token is signed with a ECDSA private key but "EC256" is NOT in the list of accepted algorithms.
1. Add validation for Token.Valid and Token.Signature in the unit tests.

Add unit test cases to parse JWT tokens signed with ECDSA keys

---

cmd/jwt/main.go

Fixes
```
$ echo '{"foo":"bar"}' | jwt -key test/ed25519-private.pem -alg EdDSA -sign -
Error: error signing token: key is of invalid type
```
Signed-off-by: Alexander Yastrebov <yastrebov.alex@gmail.com>

Fixes jwt command to support EdDSA algorithm

---

cmd/jwt/main.go

Usage:
```
$ echo '{"foo":"bar"}' | ./jwt -alg none -sign - | ./jwt -alg none -verify -
```
I know that `none` method should not be used in real applications but I think `jwt` as a tool should support it.
Signed-off-by: Alexander Yastrebov <yastrebov.alex@gmail.com>

Allow `none` algorithm in jwt command

---

errors.go

This PR adds a single Unwrap function to the ValidationError.
With this function, it is possible to call `errors.Is(err, target)` or `errors.As(err, &target)` with the error returned by e.g. `ParseWithClaims`.
More specifically, it allows one to replace
```
_, err := jwt.ParseWithClaims(...)
var valErr *jwt.ValidationError
if errors.As(err, &valErr) {
if errors.Is(valErr, myErrorType) {
// do X
} else {
// do Y
}
}
```
with
```
_, err := jwt.ParseWithClaims(...)
if errors.Is(err, myErrorType) {
// do X
}  else {
// do Y
}
```

Unwrap for ValidationError

---

cmd/jwt/main.go
signing_method.go

The help message looks like:
```
-alg string
signing algorithm identifier, one of
ES256, ES384, ES512, EdDSA, HS256, HS384, HS512,
PS256, PS384, PS512, RS256, RS384, RS512, none
```
Also fixes #63
Signed-off-by: Alexander Yastrebov <yastrebov.alex@gmail.com>

cmd: list supported algorithms

---

claims.go

Added VerifyIssuer method to RegisteredClaims

---

request/extractor.go

This PR changes how the extractor expected error `ErrNoTokenInRequest ` is checked.
This allows implementations of the `Extractor` interface to wrap errors as suggested since Go 1.13. This is mainly interesting for external Extractor implementations.
This is consistent with the direction the errors are [refactored in the `jwt` package](https://github.com/golang-jwt/jwt/pull/136). I therefore allowed myself not to open an issue first.
As the two are conceptually related, I could also open a PR towards that branch if that is desired but my understanding is that PR #136 focuses on the validation errors. @oxisto WDYT?

Support `errors.Is` for token extractors

---

claims.go
errors.go
example_test.go
map_claims.go
parser_test.go

Fixes #135 by implementing `Is(err) bool` for the `ValidationError`. It both checks
for the actual inner error message as well as our error flags for maximum backwards compatibility

Implementing `Is(err) bool` to support Go 1.13 style error checking

---

token.go
token_test.go

remove unnecessary for-loop in token signing string for readability
and ...
- add testcase
- add benchmark
- improve performance slightly

remove unnecessary for loop in token signing string for readability

---

README.md

I think it would be useful to include links to general purpose extensions besides the one already included for GCP.
I've added a short description and link to the AWS counterpart of the already included GCP SigningMethod lib.

updated README.md to contain more extensions

---

README.md

Add JWT logo attribution

---

claims.go

Hi,
I noticed that the arguments in the error message for expired tokens from RegisteredClaims are in the wrong order.
Currently, it prints `13.3528857s by token is expired` but it should probably be `token is expired by 13.3528857s`.
This pull request corrects that.
Edit: Also fixed it in StandardClaims

fix: expired token error message

---

.github/workflows/build.yml
go.mod

Checking pipeline with upcoming major Go version (1.18rc1)

Add go1.18 to ci pipeline

---

README.md

Adding the excellent JWKS extension from @MicahParks to the README.

Added MicahParks/keyfunc to extensions

---

README.md

add installation guidelines to the README file 

---

cmd/jwt/main.go
ecdsa_test.go
ed25519_test.go
hmac_example_test.go
hmac_test.go
http_example_test.go
rsa_pss_test.go
rsa_test.go
test/helpers.go

`ioutil` was deprecated in [Go 1.16](https://go.dev/doc/go1.16)

chore: replace ioutil with io and os

---

types.go
types_test.go

Fixed #199 
The original issue was caused by the fact that if we use a very large
unix timestamp. The resulting value from `Time.UnixNano()`
overflows a int64, as documented here: https://pkg.go.dev/time#Time.UnixNano.
This patch works around the issue by treating the second part and
nanosecond part separately, taking the second part from `Time.Unix()`,
and the nanosecond part from `Time.Nanosecond()`, formatting them
separately, and then combining the resulting strings.
This approach allows us to correctly marshal all go `time.Time` instances,
whereas using `Time.Unix` won't give us enough precision, and either
`Time.UnixMicro` or `Time.UnixNano` would overflow at some point for
even valid `time.Time` instances.
The added benefit of this approach is that we no longer have to deal
with …

Fixed integer overflow in NumericDate.MarshalJSON

---

rsa_test.go

Claims are not used in the rsa_test.go, so probably it is better to be removed for more clarity.

Claims in rsa_test.go Table Driven Test are Unused

---

README.md

There is a v3 documentation link which is not working in v4.

fix: link update for README.md for v4

---

request/extractor.go
request/extractor_test.go

This is a rather common extractor; it extracts the JWT from the HTTP
Authorization header, expecting it to include the "Bearer " prefix.
This patterns is rather common and this snippet is repeated in enough
applications that it's probably best to just include it upstream and
allow reusing it.

Implement a BearerExtractor

---

.github/workflows/build.yml
cmd/jwt/main.go

This PR bumps the matrix of supported Go versions, adding stable go1.19

Bump matrix to support latest go version (go1.19)

---

parser.go

It's not obvious how this works from the name and similar functions. Both in why you might pass an empty object (which is common, to change the type being parsed to) and whether a nonempty object overwrites fields from the token or is overwritten by the token.

Add doc comment to ParseWithClaims

---

http_example_test.go
parser.go
token.go

Embedding a pointer version of `jwt.RegisteredClaims` in a custom claim and passing it to `ParseWithClaims` without memory allocation will lead to a crash if an empty token is presented (see #223). Unfortunately, we cannot really check for this in the function without MAJOR reflection magic, so I fear, all we can do at the moment is adjust the example and add a better description.

No pointer embedding in the example

---

parser_test.go
token.go

By default base64 decoder works in non-strict mode which allows tweaking signatures having padding without failing validation.
This creates a potential problem if application treats token value as an identifier.
For example ES256 signature has length of 64 bytes and two padding symbols (stripped by default). Therefore its base64-encoded value can only end with A, Q, g and w. In non-strict mode last symbol could be tweaked resulting in 16 distinct token values having the same signature and passing validation.
This change adds backward-compatible global config variable DecodeStrict (similar to existing DecodePaddingAllowed) that enables strict base64 decoder mode.
See also https://github.com/golang/go/issues/15656.
Signed-off-by: Alexander Yastrebov <yastrebov.alex@gmail.com>

Allow strict base64 decoding

---

errors.go
map_claims.go
validator.go

This PR adds further documentation to the validator and does an additional cleanup to make the `VerifyXXX` functions more maintanable.

Cleanup and documentation of verification functions

---

map_claims_test.go
parser_test.go

This PR adds some more test coverage to the core functionalities. Not sure what % we want to achieve?

Adding more coverage

---

token.go

this cleans up the code a bit and avoids unnecessary memory allocations

no need for string slice and call to strings.join

---

ecdsa.go
ecdsa_test.go
ed25519.go
ed25519_test.go
hmac.go
hmac_test.go
none.go
none_test.go
parser.go
parser_option.go
parser_test.go
rsa.go
rsa_pss.go
rsa_pss_test.go
rsa_test.go
signing_method.go
token.go
token_option.go
token_test.go

This PR moves `DecodeSegment` to `Parser` and `EncodeSegment` to `Token`. This will allow us to configure the behaviour of these two based on options supplied on the parser or the token (creation). This removes two previously global variables and moves them to parser options `WithStrictDecoding` and `WithPaddingAllowed`.
Note, that in order to do that, I had to redesign the way signing methods work. Previously they were given a base64 encoded signature in `Verify` and were expected to return a base64 encoded version of the signature in `Sign`. However, this made it necessary to have `DecodeSegment` and `EncodeSegment` global and was a bad design because we were repeating encoding/decoding steps for *all* signing methods. Now, `Sign` and `Verify` take an already decoded signature as a …

Moving `DecodeSegement` to `Parser`

---

example_test.go

This PR adjusts the error checking example so that a check for an invalid signature is also included.
See discussion in #143

Adjusting the error checking example

---

hmac.go
token.go

related https://github.com/golang-jwt/jwt/pull/245

add documentation to hmac `Verify` & `Sign` to detail why string is not an advisable input for key

---

.github/workflows/build.yml

This PR adds coverage reporting using coveralls.io. I still prefer codecov though, @mfridman do you have a preference?

Added coverage reporting

---

MIGRATION_GUIDE.md
README.md
parser_option.go

Last Documentation cleanups for `v5` release

---

types.go

Previously, when parsing claim values, we used `json.UnsupportedTypeError` to denote if a claim string value is not of the correct type. However, this could lead to panics if a nil value is present and the `Error` function of the `json.UnsupportedTypeError` is called, which does not check for nil types.
Instead, we just now use `ErrInvalidType` similar to the map claims.
Fixes #315

Using jwt's native `ErrInvalidType` instead of `json.UnsupportedTypeError`

---

ed25519.go
example_test.go
http_example_test.go
parser_test.go
request/extractor_example_test.go
types_test.go

This PR reformats code:
- add a whitespace after `//`;
- sort imports;
- remove unnecessary empty lines.

Format: add whitespaces, remove empty lines

---

http_example_test.go

This PR refactors examples: `io.ReadAll` is usually used for reading the response body.

Refactor example: use io.ReadAll instead of io.Copy

---

cmd/jwt/main.go
example_test.go
hmac_test.go
none_test.go
rsa_pss_test.go
validator.go

This PR refactors code:
- remove unnecessary `else`;
- replace `if-else if` with `switch`;
- decrease `if` indentation.

Refactor code by using switch instead of if-else

---

parser.go
request/extractor.go

This PR reduces the scope of ToLower for strings and can provide a significant performance gain when validating Token Strings.
```go
import (
"strings"
"testing"
)
var (
authA = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyIxMjMiOiJka2FzbDtka2FzO2xka2FzbDtka2FzbDtka2FzbDtka2FsO3NrZGw7Y216eC4sbWMsLnp4bWMueix4bWMuLHp4bWMuengsbWMsLnp4bWMuLHp4bWMuLHp4bSxjLiIsImlhdCI6MTY4MDQ0Nzg2OX0.E9n6tm0P1-Z_fj7RmGpk6RpPMQzTJuo7knKNM0sBhvk"
)
func BenchmarkBearer(b *testing.B) {
b.Run("previous", func(b *testing.B) {
b.ResetTimer()
for i := 0; i < b.N; i++ {
strings.HasPrefix(strings.ToLower(authA), "bearer ")
}
})
b.Run("now", func(b *testing.B) {
b.ResetTimer()
for i := 0; i < b.N; i++ {
strings.HasPrefix(strings.ToLower(authA[:7]), "bearer ")
}
})
}
```
```
goos: darwin
goarch: arm64
pkg: …
```

A quick way to validate token string

---

request/extractor.go
request/oauth2.go

This PR improves further this PR #302 by replacing `strings.HasPrefix(strings.ToLower(a), b) ` with `strings.EqualFold(a, b)`. `strings.ToUpper` replaced also.
Benchmark gives the results
```
goos: darwin
goarch: arm64
pkg: github.com/golang-jwt/jwt/v5/request
BenchmarkBearerExtractor
BenchmarkBearerExtractor/ToLower
BenchmarkBearerExtractor/ToLower-8         	 4398627	       261.5 ns/op	      16 B/op	       1 allocs/op
BenchmarkBearerExtractor/EqualFold
BenchmarkBearerExtractor/EqualFold-8       	41965194	        28.42 ns/op	       0 B/op	       0 allocs/op
```
Code:
```go
import (
"strings"
"testing"
)
func BenchmarkBearerExtractor(b *testing.B) {
b.Run("ToLower", func(b *testing.B) {
b.ResetTimer()
for i := 0; i < b.N; i++ {
strings.HasPrefix(strings.ToLower(authA[:7]), "bearer ")
}
}) …
```

Refactor: compare strings with strings.EqualFold

---

parser.go

Avoid use of json.NewDecoder if not needed.
I was hanging around here and I noticed #303. This is an attempt to address it. Please let me know what you think. Thanks!
Resolves #303.

Avoid use of json.NewDecoder

---

parser.go

This small PR fixes issue #340

Update ParseUnverified godoc

---

parser.go
parser_test.go
token.go

I wanted to see what this looked like by taking #328 and then adding a `PublicKeyset` with a well-defined set of keys. 
Most of this is recomendations from @oxisto and piggybacked on #328.

Key rotation with VerificationKeySet

---

example_test.go

Prevent user from misnaming or fat fingering the Validate() method implementation.

Add explicit ClaimsValidator implementation check for custom claims

---

map_claims_test.go
parser_option.go
parser_test.go
validator.go

This PR adds a new parser option `WithExpirationRequired` which makes the claim `exp` required.

feat: allow making exp claim required

---

cmd/jwt/main.go
example_test.go
hmac_example_test.go
http_example_test.go

The error after calling jwt.Parse is often omitted while other errors are checked. The lack of consistency can be a bit confusing I think, so this PR adds some of the checks in.
Resolves #309 I suppose.

Add error handling to examples

---

MIGRATION_GUIDE.md
map_claims_test.go
parser.go
validator.go
validator_test.go

Previously, we had `newValidator` as a private function. This PR exports this function so that validation can be done independtly of parsing the claim.

Exported `NewValidator`

---

ecdsa.go

The recently improved error messages have a typo in the ECDSA error messages. This PR fixes it.

Trivial: Typo fix for ECDSA error message

---

hmac.go

Error returned by `SigningMethodHMAC.Sign` is incorrect.
Implemented error handling consistent with other signing methods.

Fix incorrect error return

---

.github/workflows/build.yml
.github/workflows/lint.yml

This PR updates the CI matrix to include go1.23 and drop go1.20 from tests.

chore: bump ci tests to include go1.23

---

cmd/jwt/main.go

Some time ago (was lazy to dig history) jwt.Parse was changed to require non-nil keyFunc.
This broke `jwt -show` command that prints header and claims and does not validate the token:
```
$ echo $TOKEN | jwt -show -
Error: malformed token: token is unverifiable: no keyfunc was provided
```
This change fixes `jwt -show`.

Fix jwt -show

---

token.go

docs: typo

---

hmac_example_test.go

Update `jwt.Parse` example to use `jwt.WithValidMethods`

---

.github/workflows/build.yml
.github/workflows/lint.yml
cmd/jwt/main.go
example_test.go
http_example_test.go
parser_test.go
validator.go

This PR does 2 things:
- Adds Go 1.24 to the build matrix
- Updates to use latest golangci-lint (recently updated to /v2 https://golangci-lint.run/product/changelog/#v200)
- Fix a few code paths for common errors in example code, mainly error checks on close and prints

Bump GitHub workflows and Go versions

---

map_claims_test.go
parser_option.go
validator.go
validator_test.go

This PR implements a validation option to validate multiple audiences. It takes ideas from #426 and #427, but implements a sleaker and cleaner design.
Fixes #342

Implementing validation of multiple audiences

---

parser_option.go
validator.go
validator_test.go

Add `WithNotBeforeRequired` parser option and add test coverage

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/spell-check.yml

This PR updates the GH Actions workflows, namely
- bumps actions/checkout to v5
- adds [newly released](https://go.dev/blog/go1.25) go1.25 to matrix
- pins the spell checker to a specific hash commit

Update github workflows

---

parser_test.go

Closes #453 
Adds an additional test to parser_test.go, that validates the library can parse the valid JWT Claims in the token to a custom Go struct with different types - validates: 
-    a string
-    a number
-    an object (JSON object)
-    an array
-    a boolean
-    null
Which should provide coverage for all valid data types as per the [JSON spec](https://www.json.org/json-en.html)

Additional test for CustomClaims that validates unmarshalling behaviour
